
baseURL = "https://bitsofinfra.com/"
languageCode = "en-us"
title = "Bits of Infra"
theme = "PaperMod"

[params]
  author = "Bits of Infra Contributors"
  defaultTheme = "auto"
  showReadingTime = true
  comments = false

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Blog"
  url = "/posts/"
  weight = 2
